[package]
name = "icale-core"
version = "0.1.0"
authors = ["euiko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
js-sys = "0.3.51"
